<?php

declare(strict_types=1);

namespace Database\Seeders;

use App\Models\Badge;
use Illuminate\Database\Seeder;

class BadgeSeeder extends Seeder
{
    public function run(): void
    {
        $badges = [
            // Anniversary
            [
                'slug'           => 'anniversary-1yr',
                'name'           => '1 Tahun Bersama',
                'description'    => 'Ahli MalayaBits selama 1 tahun. Terima kasih atas sokongan anda!',
                'category'       => 'anniversary',
                'icon'           => 'fa-calendar-check',
                'color'          => '#3b82f6',
                'criteria_type'  => 'anniversary',
                'criteria_value' => 1,
                'sort_order'     => 10,
            ],
            [
                'slug'           => 'anniversary-2yr',
                'name'           => '2 Tahun Bersama',
                'description'    => 'Ahli MalayaBits selama 2 tahun. Setia bersama kami!',
                'category'       => 'anniversary',
                'icon'           => 'fa-calendar-check',
                'color'          => '#22c55e',
                'criteria_type'  => 'anniversary',
                'criteria_value' => 2,
                'sort_order'     => 20,
            ],
            [
                'slug'           => 'anniversary-3yr',
                'name'           => '3 Tahun Bersama',
                'description'    => 'Ahli MalayaBits selama 3 tahun. Tiga tahun penuh kenangan!',
                'category'       => 'anniversary',
                'icon'           => 'fa-calendar-check',
                'color'          => '#f59e0b',
                'criteria_type'  => 'anniversary',
                'criteria_value' => 3,
                'sort_order'     => 30,
            ],
            [
                'slug'           => 'anniversary-4yr',
                'name'           => '4 Tahun Bersama',
                'description'    => 'Ahli MalayaBits selama 4 tahun. Kesetiaan anda kami hargai!',
                'category'       => 'anniversary',
                'icon'           => 'fa-calendar-check',
                'color'          => '#f97316',
                'criteria_type'  => 'anniversary',
                'criteria_value' => 4,
                'sort_order'     => 40,
            ],
            [
                'slug'           => 'anniversary-5yr',
                'name'           => '5 Tahun Bersama',
                'description'    => 'Ahli MalayaBits selama 5 tahun. Anda adalah tiang komuniti kami!',
                'category'       => 'anniversary',
                'icon'           => 'fa-crown',
                'color'          => '#a855f7',
                'criteria_type'  => 'anniversary',
                'criteria_value' => 5,
                'sort_order'     => 50,
            ],

            // Uploader
            [
                'slug'           => 'upload-first',
                'name'           => 'Muat Naik Sulung',
                'description'    => 'Torrent pertama anda telah dimuat naik. Selamat datang ke komuniti penyumbang!',
                'category'       => 'uploader',
                'icon'           => 'fa-upload',
                'color'          => '#6366f1',
                'criteria_type'  => 'total_uploads',
                'criteria_value' => 1,
                'sort_order'     => 110,
            ],
            [
                'slug'           => 'upload-25',
                'name'           => 'Penyumbang Aktif',
                'description'    => 'Telah memuat naik 25 torrent. Teruskan sumbangan anda!',
                'category'       => 'uploader',
                'icon'           => 'fa-upload',
                'color'          => '#6366f1',
                'criteria_type'  => 'total_uploads',
                'criteria_value' => 25,
                'sort_order'     => 120,
            ],
            [
                'slug'           => 'upload-100',
                'name'           => 'Penyumbang Komited',
                'description'    => 'Telah memuat naik 100 torrent. Sumbangan anda sangat bermakna!',
                'category'       => 'uploader',
                'icon'           => 'fa-upload',
                'color'          => '#8b5cf6',
                'criteria_type'  => 'total_uploads',
                'criteria_value' => 100,
                'sort_order'     => 130,
            ],
            [
                'slug'           => 'upload-250',
                'name'           => 'Penyumbang Pakar',
                'description'    => 'Telah memuat naik 250 torrent. Anda adalah tonggak komuniti!',
                'category'       => 'uploader',
                'icon'           => 'fa-upload',
                'color'          => '#7c3aed',
                'criteria_type'  => 'total_uploads',
                'criteria_value' => 250,
                'sort_order'     => 140,
            ],
            [
                'slug'           => 'upload-500',
                'name'           => 'Legenda Kandungan',
                'description'    => 'Telah memuat naik 500 torrent. Seorang legenda sejati MalayaBits!',
                'category'       => 'uploader',
                'icon'           => 'fa-crown',
                'color'          => '#fbbf24',
                'criteria_type'  => 'total_uploads',
                'criteria_value' => 500,
                'sort_order'     => 150,
            ],

            // Seeder
            [
                'slug'           => 'seed-10',
                'name'           => 'Pelayar Pemula',
                'description'    => 'Sedang menyemai sekurang-kurangnya 10 torrent. Terima kasih menolong komuniti!',
                'category'       => 'seeder',
                'icon'           => 'fa-satellite-dish',
                'color'          => '#10b981',
                'criteria_type'  => 'active_seedings',
                'criteria_value' => 10,
                'sort_order'     => 210,
            ],
            [
                'slug'           => 'seed-50',
                'name'           => 'Pelayar Setia',
                'description'    => 'Sedang menyemai sekurang-kurangnya 50 torrent. Anda adalah tulang belakang tracker!',
                'category'       => 'seeder',
                'icon'           => 'fa-satellite-dish',
                'color'          => '#059669',
                'criteria_type'  => 'active_seedings',
                'criteria_value' => 50,
                'sort_order'     => 220,
            ],
            [
                'slug'           => 'seed-100',
                'name'           => 'Pelayar Agung',
                'description'    => 'Sedang menyemai sekurang-kurangnya 100 torrent. Anda adalah wira komuniti!',
                'category'       => 'seeder',
                'icon'           => 'fa-satellite-dish',
                'color'          => '#047857',
                'criteria_type'  => 'active_seedings',
                'criteria_value' => 100,
                'sort_order'     => 230,
            ],
            [
                'slug'           => 'seed-300',
                'name'           => 'Pelayar Gemilang',
                'description'    => 'Sedang menyemai sekurang-kurangnya 300 torrent. Dedikasi anda sungguh luar biasa!',
                'category'       => 'seeder',
                'icon'           => 'fa-satellite-dish',
                'color'          => '#065f46',
                'criteria_type'  => 'active_seedings',
                'criteria_value' => 300,
                'sort_order'     => 240,
            ],
            [
                'slug'           => 'seed-500',
                'name'           => 'Pelayar Legenda',
                'description'    => 'Sedang menyemai sekurang-kurangnya 500 torrent. Anda adalah legenda pelayar MalayaBits!',
                'category'       => 'seeder',
                'icon'           => 'fa-crown',
                'color'          => '#fbbf24',
                'criteria_type'  => 'active_seedings',
                'criteria_value' => 500,
                'sort_order'     => 250,
            ],

            // Ratio
            [
                'slug'           => 'ratio-1',
                'name'           => 'Nisbah Seimbang',
                'description'    => 'Nisbah muat naik/turun melebihi 1.0. Anda menyumbang lebih dari yang diambil!',
                'category'       => 'ratio',
                'icon'           => 'fa-balance-scale',
                'color'          => '#0ea5e9',
                'criteria_type'  => 'ratio',
                'criteria_value' => 1.0,
                'sort_order'     => 310,
            ],
            [
                'slug'           => 'ratio-2',
                'name'           => 'Nisbah Baik',
                'description'    => 'Nisbah muat naik/turun melebihi 2.0. Anda menyumbang dua kali ganda!',
                'category'       => 'ratio',
                'icon'           => 'fa-balance-scale',
                'color'          => '#38bdf8',
                'criteria_type'  => 'ratio',
                'criteria_value' => 2.0,
                'sort_order'     => 315,
            ],
            [
                'slug'           => 'ratio-3',
                'name'           => 'Nisbah Hebat',
                'description'    => 'Nisbah muat naik/turun melebihi 3.0. Penyumbang yang sangat berdedikasi!',
                'category'       => 'ratio',
                'icon'           => 'fa-balance-scale',
                'color'          => '#3b82f6',
                'criteria_type'  => 'ratio',
                'criteria_value' => 3.0,
                'sort_order'     => 317,
            ],
            [
                'slug'           => 'ratio-5',
                'name'           => 'Nisbah Cemerlang',
                'description'    => 'Nisbah muat naik/turun melebihi 5.0. Penyumbang luar biasa!',
                'category'       => 'ratio',
                'icon'           => 'fa-balance-scale',
                'color'          => '#2563eb',
                'criteria_type'  => 'ratio',
                'criteria_value' => 5.0,
                'sort_order'     => 320,
            ],
            [
                'slug'           => 'ratio-10',
                'name'           => 'Nisbah Legenda',
                'description'    => 'Nisbah muat naik/turun melebihi 10.0. Anda adalah inspirasi kepada semua!',
                'category'       => 'ratio',
                'icon'           => 'fa-crown',
                'color'          => '#1d4ed8',
                'criteria_type'  => 'ratio',
                'criteria_value' => 10.0,
                'sort_order'     => 330,
            ],

            // Community
            [
                'slug'           => 'comment-10',
                'name'           => 'Pengulas Aktif',
                'description'    => 'Telah menulis 10 ulasan. Suara anda penting di sini!',
                'category'       => 'community',
                'icon'           => 'fa-comment',
                'color'          => '#ec4899',
                'criteria_type'  => 'total_comments',
                'criteria_value' => 10,
                'sort_order'     => 410,
            ],
            [
                'slug'           => 'comment-50',
                'name'           => 'Pengulas Setia',
                'description'    => 'Telah menulis 50 ulasan. Anda menghidupkan komuniti dengan pendapat anda!',
                'category'       => 'community',
                'icon'           => 'fa-comment',
                'color'          => '#db2777',
                'criteria_type'  => 'total_comments',
                'criteria_value' => 50,
                'sort_order'     => 420,
            ],
            [
                'slug'           => 'comment-100',
                'name'           => 'Pengulas Pakar',
                'description'    => 'Telah menulis 100 ulasan. Keaktifan anda sungguh menakjubkan!',
                'category'       => 'community',
                'icon'           => 'fa-comment',
                'color'          => '#be185d',
                'criteria_type'  => 'total_comments',
                'criteria_value' => 100,
                'sort_order'     => 430,
            ],

            // Special
            [
                'slug'           => 'bon-pool-donor',
                'name'           => 'Penyumbang Kolam BON',
                'description'    => 'Telah menyumbang ke Kolam BON untuk membuka kunci freeleech global. Mulia!',
                'category'       => 'special',
                'icon'           => 'fa-coins',
                'color'          => '#d97706',
                'criteria_type'  => 'bon_pool',
                'criteria_value' => 1,
                'sort_order'     => 510,
            ],
        ];

        foreach ($badges as $badge) {
            Badge::updateOrCreate(['slug' => $badge['slug']], $badge);
        }
    }
}
